apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 848224205131.dkr.ecr.us-east-1.amazonaws.com/assignment1-repo:db_0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pw
      imagePullSecrets:
        - name: ecr-secret