apiVersion: v1
kind: Pod
metadata:
  name: db-v1
  labels:
    app: mysql
spec:
  containers:
    - image: 848224205131.dkr.ecr.us-east-1.amazonaws.com/assignment1-repo:db_0.1
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
  imagePullSecrets:
    - name: ecr-secret