apiVersion: v1
kind: Service
metadata:
   name: mysql
   namespace: database
   labels:
     app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306