apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: application
  labels:
    app: employees
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000