apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: application
spec:
  selector:
    matchLabels:
      app: employees
  replicas: 3
  template:
     metadata:
       labels:
         app: employees
     spec:
       containers:
         - image: 848224205131.dkr.ecr.us-east-1.amazonaws.com/assignment1-repo:app_1.1
           name: app
           env:
             - name: DBPORT
               value: "3306"
             - name: DBHOST
               value: mysql.database.svc.cluster.local
             - name: DBUSER
               value: root
             - name: DATABASE
               value: employees
             - name: DBPWD
               value: pw
             - name: APP_COLOR
               value: blue
           ports:
             - containerPort: 8080
               protocol: TCP